### PR TITLE
Added min/max Height/Width + updated Demo

### PR DESCRIPTION
**Pull request by DarkSideOfMo0n**
This will allow to put the attributes min-height, max-height, min-width and max-width on a child. If one of this attributes is set child can not grow smaller/bigger than its min max.

### CODE REVIEW

**Comment by vpusher** [comment]
@PascalLaier you need to declare the new properties as part of the component so you don't need to pass them in your `_isWithinConstraints` method.

**Review by vpusher — COMMENTED** [review]
Please declare the missing properties

**Comment by DarkSideOfMo0n** [comment]
Hi @vpusher, I´m not quite sure what you mean? Since these properties are the properties of player/child and can be different for every child. We may could write an behavior for the children of the grid which then has those properties.

**Comment by vpusher** [comment]
@PascalLaier I was thinking about 2 globals properties on the grid itself, so we can apply your behavior on all tiles by default. Then, if some tiles have their own mix/max attributes, they override the default. I will push this update on your branch asap.

What about ?

**Comment by DarkSideOfMo0n** [comment]
@vpusher  Yes this sounds like a great idea. Will defnitly do that.

**Pull request merged**
